'use client';

import { useSearchParams } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow, TableCaption } from '@/components/ui/table';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Eye, FileText, XCircle, ArrowRight, Info, Separator, Variable, FlaskConical } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { Tooltip, TooltipProvider, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

const formatCurrencyParentheses = (value: number) => {
  if (value < 0) {
    return `(${new Intl.NumberFormat('en-US').format(Math.abs(value))})`;
  }
  return new Intl.NumberFormat('en-US').format(value);
};

const cashFlowStatementData = {
  years: ['2023', '2022'],
  lineItems: [
    { label: 'Net income', values: [80000, 75000], id: 'net-income' },
    { label: 'Depreciation', values: [30000, 28000], id: 'depreciation' },
    { label: 'Increase in accounts receivable', values: [-40000, -20000], id: 'ar-increase', isHighlighted: true },
    { label: 'Increase in inventory', values: [-90000, -30000], id: 'inventory-increase', isHighlighted: true },
    { label: 'Net cash from operating activities', values: [-20000, 53000], id: 'cfo', isBold: true, isSubtotal: true, isHighlighted: true },
    
    { label: 'Purchase of property, plant, and equipment', values: [-50000, -45000], id: 'capex' },
    { label: 'Sale of equipment', values: [60000, 5000], id: 'asset-sale', isHighlighted: true },
    { label: 'Net cash from investing activities', values: [10000, -40000], id: 'cfi', isBold: true, isSubtotal: true, isHighlighted: true },

    { label: 'Net common stock repurchased', values: [-5000, -10000], id: 'buybacks' },
    { label: 'Payment of dividends', values: [-15000, -12000], id: 'dividends' },
    { label: 'Net cash from financing activities', values: [-20000, -22000], id: 'cff', isBold: true, isSubtotal: true },
    
    { label: 'Net decrease in cash', values: [-30000, -9000], id: 'net-cash-change', isBold: true, isSubtotal: true },
    { label: 'Cash at beginning of year', values: [100000, 109000], id: 'cash-begin' },
    { label: 'Cash at end of year', values: [70000, 100000], id: 'cash-end', isBold: true, isDoubleUnderlined: true },
  ],
};

const explanations: Record<string, { title: string; content: string }> = {
    'net-income': { title: 'Net Income', content: 'The starting point. This is the accounting profit from the Income Statement, but it is not cash.' },
    'depreciation': { title: 'Depreciation', content: 'This is a non-cash expense. Since no cash actually left the company, we add it back to reconcile to cash flow.' },
    'ar-increase': { title: 'Increase in Accounts Receivable', content: "This means customers haven't paid for goods/services they received. It's a use of cash, so it's subtracted." },
    'inventory-increase': { title: 'Increase in Inventory', content: 'The company spent cash to buy or build inventory that hasn\'t been sold yet. It\'s a use of cash, so it\'s subtracted.' },
    'cfo': { title: 'Net Cash from Operating Activities', content: "The most important line. It's the cash generated by the company's core business. A negative number here is a major red flag." },
    'capex': { title: 'Purchase of PP&E (CapEx)', content: 'Cash spent on long-term assets like factories and machinery. A necessary investment for growth.' },
    'asset-sale': { title: 'Sale of Equipment', content: 'Cash received from selling old assets. A large, one-time sale can distort the picture of investing activities. An unusually large sale is a red flag.' },
    'cfi': { title: 'Net Cash from Investing Activities', content: 'Total cash flow from investment activities. Usually negative for a growing company. A positive number may indicate the company is selling assets to survive.' },
    'buybacks': { title: 'Net Common Stock Repurchased', content: 'Cash used to buy back the company\'s own shares, returning capital to shareholders. A positive sign if done at good prices.' },
    'dividends': { title: 'Payment of Dividends', content: 'Cash paid out directly to shareholders. A sign of a mature, profitable company.' },
    'cff': { title: 'Net Cash from Financing Activities', content: 'Total cash flow between the company and its owners/creditors. Often negative for healthy, mature companies.' },
    'net-cash-change': { title: 'Net Decrease in Cash', content: 'The sum of all cash flows (CFO + CFI + CFF). It shows the total change in the company\'s cash balance for the period.' },
    'cash-begin': { title: 'Cash at Beginning of Year', content: "The cash balance at the start of the year. This must match last year's ending cash on the balance sheet." },
    'cash-end': { title: 'Cash at End of Year', content: "The final cash balance. This must match the cash on this year's balance sheet." },
};

const InfoTooltip = ({ itemId }: { itemId: string }) => {
  const explanation = explanations[itemId];
  if (!explanation) return null;
  return (
    <TooltipProvider><Tooltip>
      <TooltipTrigger asChild><Info className="h-3.5 w-3.5 text-muted-foreground ml-2 cursor-help" /></TooltipTrigger>
      <TooltipContent className="max-w-xs p-3">
        <p className="font-bold mb-1">{explanation.title}</p>
        <p className="text-sm">{explanation.content}</p>
      </TooltipContent>
    </Tooltip></TooltipProvider>
  );
};


const redFlags = [
    {
        title: "Red Flag 1: Negative Cash Flow from Operations (CFO)",
        icon: XCircle,
        description: "The most critical red flag. Despite reporting a healthy Net Income of $80k, the company had a negative cash flow from its core business operations of -$20k. This means the business is burning through cash just to operate. This is often caused by major increases in Accounts Receivable (customers not paying) or Inventory (unsold products piling up), both of which are happening here. A business that cannot generate cash from its operations is not sustainable."
    },
    {
        title: "Red Flag 2: Funding Operations by Selling Assets",
        icon: XCircle,
        description: "The company's Cash Flow from Investing is positive ($10k), which is usually a bad sign. This positive cash flow is entirely due to a large '$60k Sale of equipment'. The company is selling off its productive assets (PP&E) to generate cash, likely to cover the shortfall from its negative operating cash flow. This is like selling your tools to pay your rent—it's a short-term fix that harms the company's long-term ability to operate and grow."
    }
]

export default function AnalyzeCashFlowStatementExercisePage() {
  const searchParams = useSearchParams();
  const fromStep = searchParams.get('from');

  return (
    <>
      <Alert variant="destructive" className="mb-6 bg-amber-50 dark:bg-amber-900/20 border-amber-300 dark:border-amber-700">
          <Info className="h-4 w-4 text-amber-500" />
          <AlertDescription className="text-amber-800 dark:text-amber-300 text-xs">
              For educational use only. Not financial or tax advice. Consult a licensed advisor before making major decisions.
          </AlertDescription>
      </Alert>
      <div className="mb-8">
        <h1 className="text-3xl font-bold font-headline">Exercise: Analyze a Cash Flow Statement</h1>
        <p className="text-muted-foreground mt-2">Apply your knowledge by spotting the red flags in this cash flow statement.</p>
      </div>
       <div className="space-y-6">
        <Alert>
          <FileText className="h-4 w-4" />
          <AlertTitle className="font-headline">Your Task</AlertTitle>
          <AlertDescription className="prose prose-sm max-w-none dark:prose-invert">
            <p>You are an analyst reviewing the cash flow statement for 'Example Corp.' At first glance, net income looks positive. However, there are at least two significant red flags hidden in the numbers that suggest the company is in serious financial trouble.</p>
            <p className="font-semibold">Your job is to identify these two red flags. Write them down on a piece of paper or in a document, explaining why they are concerning. When you think you have the answers, check them against the answer key below.</p>
          </AlertDescription>
        </Alert>

        <Card>
            <CardHeader>
                <CardTitle className="font-headline text-xl">Example Corp. - Statement of Cash Flows</CardTitle>
                <CardDescription>
                    Remember: a healthy business should consistently generate positive cash flow from operations — everything else is secondary.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Line Item</TableHead>
                            <TableHead className="text-right">2023</TableHead>
                            <TableHead className="text-right">2022</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {cashFlowStatementData.lineItems.map((item, index) => (
                        <TableRow key={index} className={item.isHighlighted ? "bg-amber-100/50 dark:bg-amber-900/30" : (item.isSubtotal ? "bg-muted/50" : "")}>
                            <TableCell className={`font-medium ${item.isBold ? 'font-bold' : ''} flex items-center`}>
                              {item.label}
                              <InfoTooltip itemId={item.id} />
                            </TableCell>
                            <TableCell className={`text-right ${item.isBold ? 'font-bold' : ''}`}>
                            {formatCurrencyParentheses(item.values[0])}
                            </TableCell>
                            <TableCell className={`text-right ${item.isBold ? 'font-bold' : ''}`}>
                            {formatCurrencyParentheses(item.values[1])}
                            </TableCell>
                        </TableRow>
                        ))}
                    </TableBody>
                     <TableCaption>All figures are in thousands ($)</TableCaption>
                </Table>
            </CardContent>
        </Card>
        
        <Card className="bg-primary/5 border-primary/20">
          <CardHeader>
            <CardTitle>Reveal the Answer Key</CardTitle>
            <CardDescription>Once you've completed the exercise, click below to check your answers.</CardDescription>
          </CardHeader>
          <CardContent>
            <Accordion type="single" collapsible className="w-full">
              <AccordionItem value="answers">
                <AccordionTrigger>
                    <div className="flex items-center">
                        <Eye className="mr-2 h-4 w-4"/>
                        Click to Reveal Answer Key
                    </div>
                </AccordionTrigger>
                <AccordionContent className="pt-4 space-y-4">
                  {redFlags.map(flag => (
                    <Alert key={flag.title} variant="destructive">
                        <flag.icon className="h-4 w-4" />
                        <AlertTitle className="font-semibold">{flag.title}</AlertTitle>
                        <AlertDescription>
                            {flag.description}
                        </AlertDescription>
                    </Alert>
                  ))}
                  <Alert variant="default" className="border-blue-500/50 bg-blue-50/50 dark:bg-blue-900/20">
                      <AlertTitle className="font-bold text-blue-700 dark:text-blue-300">Bonus Analysis</AlertTitle>
                      <AlertDescription>
                        <p>A sharp rise in both inventory and accounts receivable at the same time can be a signal of 'channel stuffing'—a practice where a company aggressively sends product to distributors to book revenue, even if the end demand isn't there. If you were an investor or lender, what follow-up questions would you ask management after seeing this statement?</p>
                      </AlertDescription>
                  </Alert>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </CardContent>
        </Card>

        <Card className="bg-primary/5 border-primary/20 text-center">
            <CardHeader>
                <CardTitle className="font-headline">Continue Your Journey</CardTitle>
                <CardDescription>
                    Now that you have applied your knowledge, return to the Invest Like a Pro roadmap to continue your analysis.
                </CardDescription>
            </CardHeader>
            <CardContent>
                 <Button asChild>
                    <Link href={`/roadmaps/invest-like-a-pro${fromStep ? `#${fromStep}` : ''}`}>
                        Return to the Invest Like a Pro Roadmap
                        <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                </Button>
            </CardContent>
        </Card>

      </div>
    </>
  );
}
